M48
; DRILL file {KiCad (6.0.10)} date Wed Feb 15 21:48:48 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-02-15T21:48:48-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.10)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0472
%
G90
G05
T1
X8.2381Y-3.035
X8.435Y-2.8381
X8.435Y-3.2319
X8.5334Y-2.8381
X8.5334Y-3.2319
T0
M30
